# version: "3"
services:
  backend:
    container_name: ${SERVICE_NAME:-gamafication-node-backend}
    build: .
    ports:
      - ${SERVICE_PORT:-8000}:8000
    restart: always
    depends_on:
      - db
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done;
             npx prisma migrate dev --name init;
             node dist/index.js"
    networks:
      - gamafication-network-dev

  db:
    image: postgres:17
    container_name: ${SERVICE_NAME_DB:-gamafication-db}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-gamafication}
    ports:
      - ${SERVICE_PORT_DB:-5432}:5432
    volumes:
      - /home/ubuntu/ALL_VOLUMES/gamafication-db-dev/postgres:/var/lib/postgresql/data
    networks:
      - gamafication-network-dev

networks:
  gamafication-network-dev:
    driver: bridge