version: "3"
services:
  backend:
    container_name: gamafication-node-backend
    build: .
    ports:
      - 8000:8000
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    depends_on:
      - db
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done;
             npx prisma migrate dev --name init;
             node dist/index.js"

  db:
    image: postgres:latest
    container_name: gamafication-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gamafication
    ports:
      - "5434:5432"
    volumes:
      - "/home/ubuntu/ALL_VOLUMES/gamafication-node-backend/postgres:/var/lib/postgresql/data"

