version: "3"
services:
  backend:
    container_name: gamafication-node-backend
    build: .
    ports:
      - 8000:8000
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/gamafication
    depends_on:
      - db
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done;
             npx prisma migrate dev --name init;
             node dist/index.js"

  db:
    image: postgres:latest
    container_name: gamafication-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gamafication
    ports:
      - "5434:5432"
    volumes:
      - "/home/ubuntu/ALL_VOLUMES/gamafication-node-backend/postgres:/data/db"
